import time

import pytest

from .pages.analytics_page import AnalyticsPage
from .pages.dialogs_page import FwUpdateDialogPage
from .pages.email_entry_page import EmailEntryPage
from .pages.home_page import HomePage
from .pages.settings_page import SettingsPage
from .pages.welcome_page import WelcomePage


def initial_setup_non_molding(driver):
    analytics_page = AnalyticsPage(driver)
    dialog_page = FwUpdateDialogPage(driver)
    email_entry_page = EmailEntryPage(driver)
    home_page = HomePage(driver)
    welcome_page = WelcomePage(driver)
    welcome_page.should_be_correct_welcome_title()
    welcome_page.tap_welcome_screen_get_started()
    email_entry_page.should_be_email_entry_title()
    email_entry_page.tap_no_thanks_button()
    analytics_page.tap_share_analytics_button()
    home_page.wait_for_connection()
    dialog_page.check_dialog_and_close_it()
    home_page.should_be_connected_state()


class TestMenuPage:
    def test_all_items_appear_on_settings_screen(self, driver):
        initial_setup_non_molding(driver)
        home_page = HomePage(driver)
        settings_page = SettingsPage(driver)
        home_page.should_be_earbuds_name()
        home_page.should_be_settings_icon()
        home_page.tap_settings_icon()
        settings_page.should_be_settings_title()
        settings_page.should_be_back_arrow()
        settings_page.should_be_name_item()
        settings_page.should_be_single_tap_switcher()
        settings_page.should_be_left_single_tap_item()
        settings_page.should_be_right_single_tap_item()
        settings_page.should_be_double_tap_switcher()
        settings_page.should_be_left_double_tap_item()
        settings_page.should_be_right_double_tap_item()
        settings_page.scroll_down_settings_screen()
        settings_page.should_be_dark_mode_item()
        settings_page.should_be_language_item()

    def test_edit_name_initial_state(self, driver):
        initial_setup_non_molding(driver)
        home_page = HomePage(driver)
        settings_page = SettingsPage(driver)
        home_page.should_be_earbuds_name()
        home_page.should_be_settings_icon()
        home_page.tap_settings_icon()
        settings_page.should_be_settings_title()
        settings_page.should_be_back_arrow()
        settings_page.should_be_name_item()
        settings_page.tap_name_item()
        settings_page.should_be_edit_name_title()
        settings_page.should_be_name_title()
        settings_page.should_be_name_input()
        settings_page.should_be_name_input_clear()
        settings_page.should_be_edit_name_hint()
        settings_page.should_be_update_name_button()
        settings_page.should_be_disabled_update_button()

    def test_edit_name_button_state(self, driver):
        initial_setup_non_molding(driver)
        home_page = HomePage(driver)
        settings_page = SettingsPage(driver)
        home_page.should_be_earbuds_name()
        home_page.should_be_settings_icon()
        home_page.tap_settings_icon()
        settings_page.should_be_settings_title()
        settings_page.should_be_back_arrow()
        settings_page.should_be_name_item()
        settings_page.tap_name_item()
        settings_page.should_be_edit_name_title()
        settings_page.should_be_name_title()
        settings_page.should_be_name_input()
        settings_page.should_be_name_input_clear()
        settings_page.should_be_edit_name_hint()
        settings_page.should_be_update_name_button()
        settings_page.should_be_disabled_update_button()
        settings_page.clear_name_input_field()
        settings_page.should_be_edit_name_hint()
        settings_page.should_be_disabled_update_button()
        settings_page.enter_4_letter_name()
        settings_page.should_be_edit_name_hint()
        settings_page.should_be_enabled_update_button()

    def test_edit_name_correct_number_of_symbols(self, driver):
        initial_setup_non_molding(driver)
        home_page = HomePage(driver)
        settings_page = SettingsPage(driver)
        home_page.should_be_earbuds_name()
        home_page.should_be_settings_icon()
        home_page.tap_settings_icon()
        settings_page.should_be_settings_title()
        settings_page.should_be_back_arrow()
        settings_page.should_be_name_item()
        settings_page.tap_name_item()
        settings_page.should_be_edit_name_title()
        settings_page.should_be_name_title()
        settings_page.should_be_name_input()
        settings_page.should_be_name_input_clear()
        settings_page.clear_name_input_field()
        settings_page.should_be_empty_input_field()
        settings_page.should_be_0_letters_shown_for_empty_input_field()
        settings_page.enter_4_letter_name()
        settings_page.should_be_4_letter_name()
        settings_page.should_be_4_letters_shown_for_4_letters_name()
        settings_page.enter_11_letter_name()
        settings_page.should_be_11_letter_name()
        settings_page.should_be_11_letters_shown_for_4_letters_name()
        settings_page.enter_16_letter_name()
        settings_page.should_be_16_letter_name()
        settings_page.should_be_16_letters_shown_for_4_letters_name()
        settings_page.enter_over_max_letter_name()
        settings_page.should_be_16_letter_name()
        settings_page.should_be_16_letters_shown_for_4_letters_name()

    def test_disabled_single_tap(self, driver):
        initial_setup_non_molding(driver)
        home_page = HomePage(driver)
        settings_page = SettingsPage(driver)
        home_page.should_be_earbuds_name()
        home_page.should_be_settings_icon()
        home_page.tap_settings_icon()
        time.sleep(2)
        settings_page.should_be_settings_title()
        settings_page.single_tap_enabled_check()
        settings_page.should_be_single_tap_switcher()
        settings_page.should_be_left_single_tap_item()
        settings_page.should_be_right_single_tap_item()
        settings_page.toggle_single_tap_state()
        time.sleep(2)
        settings_page.single_tap_disabled_check()
        settings_page.should_be_single_tap_switcher()
        settings_page.should_not_be_left_single_tap_item()
        settings_page.should_not_be_right_single_tap_item()
        settings_page.toggle_single_tap_state()
        time.sleep(2)
        settings_page.single_tap_enabled_check()
        settings_page.should_be_single_tap_switcher()
        settings_page.should_be_left_single_tap_item()
        settings_page.should_be_right_single_tap_item()

    def test_single_tap_left_screen(self, driver):
        initial_setup_non_molding(driver)
        home_page = HomePage(driver)
        settings_page = SettingsPage(driver)
        home_page.should_be_earbuds_name()
        home_page.should_be_settings_icon()
        home_page.tap_settings_icon()
        time.sleep(2)
        settings_page.should_be_settings_title()
        settings_page.should_be_single_tap_switcher()
        settings_page.should_be_left_single_tap_item()
        settings_page.tap_left_single_tap_item()
        settings_page.should_be_single_tap_items_screen()

    def test_single_tap_right_screen(self, driver):
        initial_setup_non_molding(driver)
        home_page = HomePage(driver)
        settings_page = SettingsPage(driver)
        home_page.should_be_earbuds_name()
        home_page.should_be_settings_icon()
        home_page.tap_settings_icon()
        time.sleep(2)
        settings_page.should_be_settings_title()
        settings_page.should_be_single_tap_switcher()
        settings_page.should_be_right_single_tap_item()
        settings_page.tap_right_single_tap_item()
        settings_page.should_be_single_tap_items_screen()

    def test_every_selection_left_single_tap(self, driver):
        initial_setup_non_molding(driver)
        home_page = HomePage(driver)
        settings_page = SettingsPage(driver)
        home_page.should_be_earbuds_name()
        home_page.should_be_settings_icon()
        home_page.tap_settings_icon()
        time.sleep(2)
        settings_page.should_be_settings_title()
        settings_page.should_be_single_tap_switcher()
        settings_page.should_be_left_single_tap_item()
        settings_page.tap_left_single_tap_item()
        settings_page.should_be_single_tap_items_screen()
        settings_page.select_single_tap_play_pause()
        settings_page.save_selection()
        settings_page.should_be_play_pause_selected_single_tap_left()
        settings_page.tap_left_single_tap_item()
        settings_page.should_be_single_tap_items_screen()
        settings_page.select_single_tap_next_track()
        settings_page.save_selection()
        settings_page.should_be_next_track_selected_single_tap_left()
        settings_page.tap_left_single_tap_item()
        settings_page.should_be_single_tap_items_screen()
        settings_page.select_single_tap_previous_track()
        settings_page.save_selection()
        settings_page.should_be_previous_track_selected_single_tap_left()
        settings_page.tap_left_single_tap_item()
        settings_page.should_be_single_tap_items_screen()
        settings_page.select_single_tap_volume_up()
        settings_page.save_selection()
        settings_page.should_be_volume_up_selected_single_tap_left()
        settings_page.tap_left_single_tap_item()
        settings_page.should_be_single_tap_items_screen()
        settings_page.select_single_tap_volume_down()
        settings_page.save_selection()
        settings_page.should_be_volume_down_selected_single_tap_left()

    def test_every_selection_right_single_tap(self, driver):
        initial_setup_non_molding(driver)
        home_page = HomePage(driver)
        settings_page = SettingsPage(driver)
        home_page.should_be_earbuds_name()
        home_page.should_be_settings_icon()
        home_page.tap_settings_icon()
        time.sleep(2)
        settings_page.should_be_settings_title()
        settings_page.should_be_single_tap_switcher()
        settings_page.should_be_right_single_tap_item()
        settings_page.tap_right_single_tap_item()
        settings_page.should_be_single_tap_items_screen()
        settings_page.select_single_tap_play_pause()
        settings_page.save_selection()
        settings_page.should_be_play_pause_selected_single_tap_right()
        settings_page.tap_right_single_tap_item()
        settings_page.should_be_single_tap_items_screen()
        settings_page.select_single_tap_next_track()
        settings_page.save_selection()
        settings_page.should_be_next_track_selected_single_tap_right()
        settings_page.tap_right_single_tap_item()
        settings_page.should_be_single_tap_items_screen()
        settings_page.select_single_tap_previous_track()
        settings_page.save_selection()
        settings_page.should_be_previous_track_selected_single_tap_right()
        settings_page.tap_right_single_tap_item()
        settings_page.should_be_single_tap_items_screen()
        settings_page.select_single_tap_volume_down()
        settings_page.save_selection()
        settings_page.should_be_volume_down_selected_single_tap_right()
        settings_page.tap_right_single_tap_item()
        settings_page.should_be_single_tap_items_screen()
        settings_page.select_single_tap_volume_up()
        settings_page.save_selection()
        settings_page.should_be_volume_up_selected_single_tap_right()
