import pytest

from .pages.analytics_page import AnalyticsPage
from .pages.demo_page import DemoSendCommandsPage
from .pages.dialogs_page import EditPresetsDialogPage
from .pages.eq_presets_page import EditPresetsPage
from .pages.eq_presets_page import EqPresetsPage
from .pages.home_page import HomePage
from .pages.dialogs_page import HomeScreenWelcomeDialogPage
from .pages.landing_page import LandingPage
from .pages.molding_page import MoldingPage
from .pages.tutorial_home_screen_page import TutorialHomeScreenPage
from .pages.welcome_page import WelcomePage

import time

"""That's the set of tests from all test files intended to run smoke test
Requires connected earbuds via BT classic pulled off out of the case"""


@pytest.mark.smoke_test
class TestSmokeTest:
    def test_should_be_welcome_screen(self, driver):
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.should_be_correct_welcome_subtitle()
        welcome_page.should_be_welcome_screen_button()
        welcome_page.should_be_welcome_get_started_button_text()

    @pytest.mark.xfail
    def test_should_be_welcome_screen_after_background(self, driver):
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.should_be_correct_welcome_subtitle()
        welcome_page.should_be_welcome_screen_button()
        welcome_page.should_be_welcome_get_started_button_text()
        welcome_page.background_app_for_10_seconds()
        welcome_page.should_be_correct_welcome_title()
        welcome_page.should_be_correct_welcome_subtitle()
        welcome_page.should_be_welcome_screen_button()
        welcome_page.should_be_welcome_get_started_button_text()

    def test_access_setup_code_screen(self, driver):
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.tap_where_is_my_code()
        welcome_page.should_be_correct_setup_code_title()
        welcome_page.should_be_correct_welcome_setup_code_text()
        welcome_page.close_welcome_setup_code_screen()
        welcome_page.should_be_welcome_code_screen_title()

    def test_access_demo_molding_screen(self, driver):
        welcome_page = WelcomePage(driver)
        demo_commands_page = DemoSendCommandsPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.go_to_demo_screen_code()
        welcome_page.tap_screen_code_get_started()
        time.sleep(5)
        demo_commands_page.should_be_demo_molding_screen()

    def test_access_demo_debug_screen(self, driver):
        welcome_page = WelcomePage(driver)
        demo_commands_page = DemoSendCommandsPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.go_to_demo_screen_code()
        welcome_page.tap_screen_code_get_started()
        time.sleep(5)
        demo_commands_page.should_be_demo_molding_screen()
        demo_commands_page.tap_debug_button()
        demo_commands_page.should_be_demo_debug_screen()

    def test_curring_mode_activation(self, driver):
        welcome_page = WelcomePage(driver)
        demo_commands_page = DemoSendCommandsPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.go_to_demo_screen_code()
        welcome_page.tap_screen_code_get_started()
        time.sleep(6)
        demo_commands_page.should_be_demo_molding_screen()
        demo_commands_page.tap_debug_button()
        demo_commands_page.activate_curring_mode()

    def test_should_be_analytics_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_back_arrow()
        analytics_page.should_be_analytics_title()
        analytics_page.should_be_correct_analytics_subtitle()
        analytics_page.should_be_correct_share_analytics_button_text()
        analytics_page.should_be_correct_not_share_analytics_button_text()

    def test_return_to_welcome_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_back_arrow()
        analytics_page.tap_back_arrow()
        welcome_page.should_be_correct_welcome_title()
        welcome_page.should_be_correct_welcome_subtitle()
        welcome_page.should_be_welcome_screen_button()
        welcome_page.should_be_welcome_get_started_button_text()

    def test_should_be_landing_page_after_accepting_analytics(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_back_arrow()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        landing_page.should_be_correct_landing_page_subtitle()
        landing_page.should_be_progress_bar()

    def test_should_be_landing_page_after_discarding_analytics(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_back_arrow()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_not_share_analytics_button()
        landing_page.should_be_landing_page_title()
        landing_page.should_be_correct_landing_page_subtitle()
        landing_page.should_be_progress_bar()

    def test_should_be_try_them_page(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        molding_page.should_be_try_them_page_title()
        molding_page.should_be_correct_try_them_page_subtitle()
        molding_page.should_be_main_button()

    def test_should_be_get_ready_page(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.should_be_message_title1()
        molding_page.should_be_message_title2()
        molding_page.should_be_message_title3()
        molding_page.should_be_message1()
        molding_page.should_be_message2()
        molding_page.should_be_message3()
        molding_page.should_be_smile()
        molding_page.should_be_stand_by_mirror_text()
        molding_page.should_be_main_button()

    def test_should_be_how_is_bass_page(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        molding_page.should_be_correct_how_is_bass_subtitle()
        molding_page.should_be_image_volume()
        molding_page.should_be_adjust_volume_bar()
        molding_page.should_be_cancel_button()
        molding_page.should_be_cancel_button_text()
        molding_page.tap_cancel_button()
        molding_page.should_be_get_ready_page_title()

    def test_should_start_soon_page1(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        time.sleep(19)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        molding_page.tap_cancel_button()
        molding_page.should_be_get_ready_page_title()

    def test_should_start_soon_page2(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        time.sleep(19)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(6)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        molding_page.tap_cancel_button()
        molding_page.should_be_get_ready_page_title()

    def test_cancel_molding_on_count(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        time.sleep(19)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(6)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        time.sleep(5)
        molding_page.tap_cancel_button()
        molding_page.should_be_get_ready_page_title()

    def test_molding_complete(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(12)
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        time.sleep(19)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(6)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        time.sleep(45)
        molding_page.should_be_progress_bar()
        time.sleep(40)
        molding_page.should_congratulations_title()
        molding_page.should_congratulations_subtitle()
        molding_page.should_finish_button()
        molding_page.should_finish_button_text()
        molding_page.tap_finish_button()
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.should_be_welcome_dialog_message()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_earbuds_name()
        home_page.should_be_connected_state()
        home_page.should_be_hamburger_menu()
        home_page.should_be_settings_icon()
        home_page.should_be_left_earbud_image()
        home_page.should_be_left_battery_image()
        home_page.should_be_left_battery_percents()
        home_page.should_be_right_earbud_image()
        home_page.should_be_right_battery_image()
        home_page.should_be_right_battery_percents()
        home_page.should_be_case_image()
        home_page.should_be_case_battery_image()
        home_page.should_be_case_battery_percents()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()

    def test_welcome_dialog_pops_up(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.should_be_welcome_dialog_message()
        dialog_page.should_be_take_tour_button()
        dialog_page.should_be_take_tour_button_text()
        dialog_page.should_be_no_thanks_button()
        dialog_page.should_be_no_thanks_button_text()

    def test_home_screen_connected(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        landing_page = LandingPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.should_be_welcome_dialog_message()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_earbuds_name()
        home_page.should_be_connected_state()
        home_page.should_be_hamburger_menu()
        home_page.should_be_settings_icon()
        home_page.should_be_left_earbud_image()
        home_page.should_be_left_battery_image()
        home_page.should_be_left_battery_percents()
        home_page.should_be_right_earbud_image()
        home_page.should_be_right_battery_image()
        home_page.should_be_right_battery_percents()
        home_page.should_be_case_image()
        home_page.should_be_case_battery_image()
        home_page.should_be_case_battery_percents()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()

    def test_tutorial_first_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        tutorial_page = TutorialHomeScreenPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.tap_take_tour_button()
        tutorial_page.should_be_tutorial_container()
        tutorial_page.should_be_tutorial_arrow()
        tutorial_page.should_be_main_menu_title()
        tutorial_page.should_be_main_menu_tutorial_message()
        tutorial_page.should_be_next_button()
        tutorial_page.should_be_next_button_text()
        tutorial_page.should_be_skip_tutorial_button()
        tutorial_page.should_be_skip_tutorial_button_text()
        tutorial_page.tap_skip_tutorial_button()
        home_page.should_be_earbuds_name()
        home_page.should_be_hamburger_menu()
        home_page.should_be_settings_icon()
        home_page.should_be_left_earbud_image()
        home_page.should_be_right_earbud_image()
        home_page.should_be_case_image()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()

    def test_tutorial_second_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        tutorial_page = TutorialHomeScreenPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.tap_take_tour_button()
        tutorial_page.should_be_tutorial_container()
        tutorial_page.should_be_tutorial_arrow()
        tutorial_page.should_be_main_menu_title()
        tutorial_page.tap_next_button()
        tutorial_page.should_be_tutorial_container()
        tutorial_page.should_be_tutorial_arrow()
        tutorial_page.should_be_settings_title()
        tutorial_page.should_be_settings_tutorial_message()
        tutorial_page.should_be_thanks_next_button()
        tutorial_page.should_be_thanks_next_button_text()
        tutorial_page.tap_skip_tutorial_button()
        home_page.should_be_earbuds_name()
        home_page.should_be_hamburger_menu()
        home_page.should_be_settings_icon()
        home_page.should_be_left_earbud_image()
        home_page.should_be_right_earbud_image()
        home_page.should_be_case_image()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()

    def test_tutorial_third_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        tutorial_page = TutorialHomeScreenPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.tap_take_tour_button()
        tutorial_page.should_be_tutorial_container()
        tutorial_page.should_be_tutorial_arrow()
        tutorial_page.should_be_main_menu_title()
        tutorial_page.tap_next_button()
        tutorial_page.should_be_tutorial_container()
        tutorial_page.should_be_tutorial_arrow()
        tutorial_page.should_be_settings_title()
        tutorial_page.tap_next_button()
        tutorial_page.should_be_tutorial_container()
        tutorial_page.should_be_custom_eq_title()
        tutorial_page.should_be_custom_eq_message()
        tutorial_page.should_be_got_it_button()
        tutorial_page.should_be_got_it_button_text()
        tutorial_page.tap_got_it_button()
        home_page.should_be_earbuds_name()
        home_page.should_be_hamburger_menu()
        home_page.should_be_settings_icon()
        home_page.should_be_left_earbud_image()
        home_page.should_be_right_earbud_image()
        home_page.should_be_case_image()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()

    def test_home_screen_after_closing_presets_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        landing_page = LandingPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.should_be_welcome_dialog_message()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_earbuds_name()
        home_page.should_be_connected_state()
        home_page.should_be_hamburger_menu()
        home_page.should_be_settings_icon()
        home_page.should_be_left_earbud_image()
        home_page.should_be_left_battery_image()
        home_page.should_be_left_battery_percents()
        home_page.should_be_right_earbud_image()
        home_page.should_be_right_battery_image()
        home_page.should_be_right_battery_percents()
        home_page.should_be_case_image()
        home_page.should_be_case_battery_image()
        home_page.should_be_case_battery_percents()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_eq_expand_icon()
        home_page.should_be_earbuds_name()
        home_page.should_be_connected_state()
        home_page.should_be_hamburger_menu()
        home_page.should_be_settings_icon()
        home_page.should_be_left_earbud_image()
        home_page.should_be_left_battery_image()
        home_page.should_be_left_battery_percents()
        home_page.should_be_right_earbud_image()
        home_page.should_be_right_battery_image()
        home_page.should_be_right_battery_percents()
        home_page.should_be_case_image()
        home_page.should_be_case_battery_image()
        home_page.should_be_case_battery_percents()

    def test_initial_presets_screen_setup(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.should_be_welcome_dialog_message()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()
        eq_presets_page.should_be_toolbar()
        eq_presets_page.should_be_customize_button()
        eq_presets_page.should_be_customize_button_text()
        eq_presets_page.should_be_expandable_part()
        eq_presets_page.should_be_divider_line()
        eq_presets_page.should_be_presets_title()
        eq_presets_page.should_be_edit_button()
        eq_presets_page.should_be_edit_button_text()
        eq_presets_page.should_be_add_button()
        eq_presets_page.should_be_presets_list()
        eq_presets_page.should_be_six_presets()
        eq_presets_page.should_be_initial_preset_order()

    def test_switching_between_eq_presets(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.should_be_welcome_dialog_message()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()
        eq_presets_page.should_be_toolbar()
        eq_presets_page.should_be_expandable_part()
        eq_presets_page.select_6_preset()
        eq_presets_page.select_1_preset()
        eq_presets_page.select_5_preset()
        eq_presets_page.select_2_preset()
        eq_presets_page.select_3_preset()
        eq_presets_page.select_4_preset()

    def test_access_edit_presets_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.should_be_welcome_dialog_message()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()
        eq_presets_page.should_be_toolbar()
        eq_presets_page.should_be_expandable_part()
        eq_presets_page.tap_edit_button()
        edit_preset_page.should_be_toolbar()
        edit_preset_page.should_be_back_arrow()
        edit_preset_page.should_be_edit_preset_title()
        edit_preset_page.should_be_save_button()
        edit_preset_page.should_be_save_button_text()
        edit_preset_page.should_be_presets_list()
        edit_preset_page.should_be_six_presets()
        edit_preset_page.should_be_initial_preset_order()

    def test_preset_reorder_should_be_possible(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_edit_button()
        edit_preset_page.move_first_preset_to_fourth_position()
        edit_preset_page.move_six_preset_to_second_position()
        edit_preset_page.move_three_to_four_position()

    def test_reordering_should_not_be_saved_after_tapping_back_button(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_edit_button()
        edit_preset_page.move_second_preset_to_fourth_position()
        edit_preset_page.tap_back_arrow()
        eq_presets_page.should_be_initial_preset_order()

    def test_reordering_should_be_saved_after_tapping_save_button(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_edit_button()
        edit_preset_page.move_first_preset_to_fourth_position()
        edit_preset_page.tap_save_button()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_preset_order_after_moving_ue_signature()

    def test_reorder_and_delete_first_item(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        dialog_preset_page = EditPresetsDialogPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_edit_button()
        edit_preset_page.move_first_preset_to_fourth_position()
        edit_preset_page.delete_top_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_five_presets()
        edit_preset_page.tap_save_button()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_five_presets()

    def test_cancel_preset_deletion(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        dialog_preset_page = EditPresetsDialogPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_edit_button()
        edit_preset_page.delete_sixth_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_cancel_button()
        edit_preset_page.should_be_six_presets()
        edit_preset_page.tap_save_button()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_six_presets()

    def test_delete_all_presets(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_page = HomeScreenWelcomeDialogPage(driver)
        dialog_preset_page = EditPresetsDialogPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        time.sleep(10)
        dialog_page.should_be_welcome_dialog_title()
        dialog_page.tap_no_thanks_button()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_edit_button()
        # Delete preset #6
        edit_preset_page.delete_sixth_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_five_presets()
        # Delete preset #5
        edit_preset_page.delete_fifth_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_four_presets()
        # Delete preset #4
        edit_preset_page.delete_fourth_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_three_presets()
        # Delete preset #3
        edit_preset_page.delete_third_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_two_presets()
        # Delete preset #2
        edit_preset_page.delete_top_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_one_preset()
        edit_preset_page.tap_save_button()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_one_preset()

# run with
# pytest -v --reruns 2 --tb=line -m smoke_test --html=C:\app\test_report\report.html
