import pytest

from .pages.analytics_page import AnalyticsPage
from .pages.eq_presets_page import EqPresetsPage
from .pages.home_page import HomePage
from .pages.landing_page import LandingPage
from .pages.tutorial_home_screen_page import TutorialHomeScreenPage
from .pages.welcome_page import WelcomePage

import time


class TestTutorialHomeScreen:
    pass
    # def test_tutorial_first_screen(self, driver):
    #     analytics_page = AnalyticsPage(driver)
    #     eq_presets_page = EqPresetsPage(driver)
    #     home_page = HomePage(driver)
    #     landing_page = LandingPage(driver)
    #     tutorial_page = TutorialHomeScreenPage(driver)
    #     welcome_page = WelcomePage(driver)
    #     welcome_page.should_be_correct_welcome_title()
    #     welcome_page.tap_welcome_screen_get_started()
    #     analytics_page.should_be_analytics_title()
    #     analytics_page.tap_share_analytics_button()
    #     landing_page.should_be_landing_page_title()
    #     time.sleep(10)
    #     tutorial_page.should_be_tutorial_container()
    #     tutorial_page.should_be_tutorial_arrow()
    #     tutorial_page.should_be_main_menu_title()
    #     tutorial_page.should_be_main_menu_tutorial_message()
    #     tutorial_page.should_be_next_button()
    #     tutorial_page.should_be_next_button_text()
    #     tutorial_page.should_be_skip_tutorial_button()
    #     tutorial_page.should_be_skip_tutorial_button_text()
    #     tutorial_page.tap_skip_tutorial_button()
    #     home_page.should_be_earbuds_name()
    #     home_page.should_be_hamburger_menu()
    #     home_page.should_be_settings_icon()
    #     home_page.should_be_left_earbud_image()
    #     home_page.should_be_right_earbud_image()
    #     home_page.should_be_case_image()
    #     eq_presets_page.should_be_eq_name()
    #     eq_presets_page.should_be_ue_signature_eq_selected()
    #     eq_presets_page.should_be_eq_curve_image()
    #
    # def test_tutorial_second_screen(self, driver):
    #     analytics_page = AnalyticsPage(driver)
    #     eq_presets_page = EqPresetsPage(driver)
    #     home_page = HomePage(driver)
    #     landing_page = LandingPage(driver)
    #     tutorial_page = TutorialHomeScreenPage(driver)
    #     welcome_page = WelcomePage(driver)
    #     welcome_page.should_be_correct_welcome_title()
    #     welcome_page.tap_welcome_screen_get_started()
    #     analytics_page.should_be_analytics_title()
    #     analytics_page.tap_share_analytics_button()
    #     landing_page.should_be_landing_page_title()
    #     time.sleep(10)
    #     tutorial_page.should_be_tutorial_container()
    #     tutorial_page.should_be_tutorial_arrow()
    #     tutorial_page.should_be_main_menu_title()
    #     tutorial_page.tap_next_button()
    #     tutorial_page.should_be_tutorial_container()
    #     tutorial_page.should_be_tutorial_arrow()
    #     tutorial_page.should_be_settings_title()
    #     tutorial_page.should_be_settings_tutorial_message()
    #     tutorial_page.should_be_thanks_next_button()
    #     tutorial_page.should_be_thanks_next_button_text()
    #     tutorial_page.tap_skip_tutorial_button()
    #     home_page.should_be_earbuds_name()
    #     home_page.should_be_hamburger_menu()
    #     home_page.should_be_settings_icon()
    #     home_page.should_be_left_earbud_image()
    #     home_page.should_be_right_earbud_image()
    #     home_page.should_be_case_image()
    #     eq_presets_page.should_be_eq_name()
    #     eq_presets_page.should_be_ue_signature_eq_selected()
    #     eq_presets_page.should_be_eq_curve_image()
    #
    # def test_tutorial_third_screen(self, driver):
    #     analytics_page = AnalyticsPage(driver)
    #     eq_presets_page = EqPresetsPage(driver)
    #     home_page = HomePage(driver)
    #     landing_page = LandingPage(driver)
    #     tutorial_page = TutorialHomeScreenPage(driver)
    #     welcome_page = WelcomePage(driver)
    #     welcome_page.should_be_correct_welcome_title()
    #     welcome_page.tap_welcome_screen_get_started()
    #     analytics_page.should_be_analytics_title()
    #     analytics_page.tap_share_analytics_button()
    #     landing_page.should_be_landing_page_title()
    #     time.sleep(10)
    #     tutorial_page.should_be_tutorial_container()
    #     tutorial_page.should_be_tutorial_arrow()
    #     tutorial_page.should_be_main_menu_title()
    #     tutorial_page.tap_next_button()
    #     tutorial_page.should_be_tutorial_container()
    #     tutorial_page.should_be_tutorial_arrow()
    #     tutorial_page.should_be_settings_title()
    #     tutorial_page.tap_next_button()
    #     tutorial_page.should_be_tutorial_container()
    #     tutorial_page.should_be_custom_eq_title()
    #     tutorial_page.should_be_custom_eq_message()
    #     tutorial_page.should_be_got_it_button()
    #     tutorial_page.should_be_got_it_button_text()
    #     tutorial_page.tap_got_it_button()
    #     home_page.should_be_earbuds_name()
    #     home_page.should_be_hamburger_menu()
    #     home_page.should_be_settings_icon()
    #     home_page.should_be_left_earbud_image()
    #     home_page.should_be_right_earbud_image()
    #     home_page.should_be_case_image()
    #     eq_presets_page.should_be_eq_name()
    #     eq_presets_page.should_be_ue_signature_eq_selected()
    #     eq_presets_page.should_be_eq_curve_image()
