import pytest

from .pages.analytics_page import AnalyticsPage
from .pages.demo_page import DemoSendCommandsPage
from .pages.dialogs_page import EditPresetsDialogPage
from .pages.eq_presets_page import EditPresetsPage
from .pages.eq_presets_page import EqPresetsPage
from .pages.eq_presets_page import EqPresetSetupPage
from .pages.email_entry_page import EmailEntryPage
from .pages.firmware_update_page import FirmwareUpdatePage
from .pages.home_page import HomePage
from .pages.landing_page import LandingPage
from .pages.learn_more_page import LearnMorePage
from .pages.menu_page import MenuPage
from .pages.molding_page import MoldingPage, MoldNewTipsPage
from .pages.support_page import SupportPage
from .pages.welcome_page import WelcomePage

import time

"""That's the set of tests from all test files intended to run smoke test
Requires connected earbuds via BT classic pulled off out of the case"""


@pytest.mark.smoke_test
class TestSmokeTest:
    # Welcome page
    def test_should_be_welcome_screen(self, driver):
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.should_be_correct_welcome_subtitle()
        welcome_page.should_be_welcome_screen_button()
        welcome_page.should_be_welcome_get_started_button_text()

    @pytest.mark.xfail
    def test_should_be_welcome_screen_after_background(self, driver):
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.should_be_correct_welcome_subtitle()
        welcome_page.should_be_welcome_screen_button()
        welcome_page.should_be_welcome_get_started_button_text()
        welcome_page.background_app_for_5_seconds()
        welcome_page.should_be_correct_welcome_title()
        welcome_page.should_be_correct_welcome_subtitle()
        welcome_page.should_be_welcome_screen_button()
        welcome_page.should_be_welcome_get_started_button_text()

    def test_should_be_welcome_code_screen(self, driver):
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.should_be_welcome_edit_text_input()
        welcome_page.should_be_welcome_edit_text_input_text()
        welcome_page.should_be_welcome_send_code_button()
        welcome_page.should_be_welcome_code_get_started_button_text()
        welcome_page.should_be_welcome_where_is_my_code()
        welcome_page.should_be_welcome_where_is_my_code_text()

    def test_should_be_email_entry_screen(self, driver):
        email_entry_page = EmailEntryPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        email_entry_page.should_be_back_arrow()
        email_entry_page.should_be_email_entry_title()
        email_entry_page.should_be_correct_email_entry_subtitle()
        email_entry_page.should_be_email_entry_input()
        email_entry_page.should_be_correct_sign_me_button_text()
        email_entry_page.should_be_correct_no_thanks_button_text()

    def test_return_to_welcome_screen(self, driver):
        email_entry_page = EmailEntryPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        email_entry_page.should_be_back_arrow()
        email_entry_page.tap_back_arrow()
        welcome_page.should_be_correct_welcome_title()
        welcome_page.should_be_correct_welcome_subtitle()
        welcome_page.should_be_welcome_screen_button()
        welcome_page.should_be_welcome_get_started_button_text()

    # Analytics page
    def test_should_be_analytics_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_back_arrow()
        analytics_page.should_be_analytics_title()
        analytics_page.should_be_correct_analytics_subtitle()
        analytics_page.should_be_correct_share_analytics_button_text()
        analytics_page.should_be_correct_not_share_analytics_button_text()

    # Demo page
    def test_access_demo_molding_screen(self, driver):
        welcome_page = WelcomePage(driver)
        demo_commands_page = DemoSendCommandsPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.go_to_demo_screen_code()
        welcome_page.tap_screen_code_get_started()
        time.sleep(5)
        demo_commands_page.should_be_demo_molding_screen()

    def test_access_demo_debug_screen(self, driver):
        welcome_page = WelcomePage(driver)
        demo_commands_page = DemoSendCommandsPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.go_to_demo_screen_code()
        welcome_page.tap_screen_code_get_started()
        time.sleep(5)
        demo_commands_page.should_be_demo_molding_screen()
        demo_commands_page.tap_debug_button()
        demo_commands_page.should_be_demo_debug_screen()

    def test_check_first_two_items_codes(self, driver):
        welcome_page = WelcomePage(driver)
        demo_commands_page = DemoSendCommandsPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.go_to_demo_screen_code()
        welcome_page.tap_screen_code_get_started()
        time.sleep(5)
        demo_commands_page.should_be_demo_molding_screen()
        demo_commands_page.tap_debug_button()
        demo_commands_page.should_be_demo_debug_screen()
        demo_commands_page.tap_first_commands_list_item()
        demo_commands_page.tap_second_commands_list_item()

    def test_curring_mode_activation(self, driver):
        welcome_page = WelcomePage(driver)
        demo_commands_page = DemoSendCommandsPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.go_to_demo_screen_code()
        welcome_page.tap_screen_code_get_started()
        time.sleep(6)
        demo_commands_page.should_be_demo_molding_screen()
        demo_commands_page.tap_debug_button()
        demo_commands_page.activate_curring_mode()

    # Molding page
    def test_should_be_try_them_page(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        molding_page.wait_for_connection()
        molding_page.should_be_try_them_page_title()
        molding_page.should_be_correct_try_them_page_subtitle()
        molding_page.should_be_main_button()

    def test_should_be_get_ready_page(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        molding_page.wait_for_connection()
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.should_be_message_title1()
        molding_page.should_be_message_title2()
        molding_page.should_be_message_title3()
        molding_page.should_be_message1()
        molding_page.should_be_message2()
        molding_page.should_be_message3()
        molding_page.should_be_smile()
        molding_page.should_be_stand_by_mirror_text()
        molding_page.should_be_main_button()

    def test_should_be_how_is_bass_page(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        molding_page.wait_for_connection()
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        molding_page.should_be_correct_how_is_bass_subtitle()
        molding_page.should_be_image_volume()
        molding_page.should_be_adjust_volume_bar()
        molding_page.should_be_cancel_button()
        molding_page.should_be_cancel_button_text()
        molding_page.tap_cancel_button()
        molding_page.should_be_get_ready_page_title()

    def test_should_start_soon_page1(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        molding_page.wait_for_connection()
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        time.sleep(19)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        molding_page.tap_cancel_button()
        molding_page.should_be_get_ready_page_title()

    def test_should_start_soon_page2(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        molding_page.wait_for_connection()
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        time.sleep(19)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(6)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        molding_page.tap_cancel_button()
        molding_page.should_be_get_ready_page_title()

    def test_cancel_molding_on_count(self, driver):
        analytics_page = AnalyticsPage(driver)
        welcome_page = WelcomePage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        molding_page.wait_for_connection()
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        time.sleep(19)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(6)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        time.sleep(4)
        molding_page.tap_cancel_button()
        molding_page.should_be_get_ready_page_title()

    def test_molding_complete(self, driver):
        analytics_page = AnalyticsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        molding_page.wait_for_connection()
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        time.sleep(19)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(6)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        time.sleep(45)
        molding_page.should_be_progress_bar()
        time.sleep(40)

        molding_page.should_congratulations_title()
        molding_page.should_congratulations_subtitle_after_first_molding()
        molding_page.should_be_take_the_tour_button()
        molding_page.should_be_take_the_tour_button_text()
        molding_page.should_skip_for_now_button()
        molding_page.should_skip_for_now_button_text()
        molding_page.tap_skip_for_now_button()

        home_page.should_be_earbuds_name()
        home_page.should_be_connected_state()
        home_page.should_be_hamburger_menu_icon()
        home_page.should_be_settings_icon()
        home_page.should_be_left_earbud_image()
        home_page.should_be_left_battery_image()
        home_page.should_be_left_battery_percents()
        home_page.should_be_right_earbud_image()
        home_page.should_be_right_battery_image()
        home_page.should_be_right_battery_percents()
        home_page.should_be_case_image()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()

    # Activate curing for second molding
    def test_curring_mode_activation1(self, driver):
        welcome_page = WelcomePage(driver)
        demo_commands_page = DemoSendCommandsPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.go_to_demo_screen_code()
        welcome_page.tap_screen_code_get_started()
        time.sleep(6)
        demo_commands_page.should_be_demo_molding_screen()
        demo_commands_page.tap_debug_button()
        demo_commands_page.activate_curring_mode()

    def test_molding_complete_and_open_learn_more(self, driver):
        analytics_page = AnalyticsPage(driver)
        landing_page = LandingPage(driver)
        learn_more_page = LearnMorePage(driver)
        molding_page = MoldingPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        molding_page.wait_for_connection()
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        time.sleep(19)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(6)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        time.sleep(45)
        molding_page.should_be_progress_bar()
        time.sleep(40)
        # Congratulations
        molding_page.should_congratulations_title()
        molding_page.should_congratulations_subtitle_after_first_molding()
        molding_page.should_skip_for_now_button()
        molding_page.should_skip_for_now_button_text()
        molding_page.should_be_take_the_tour_button()
        molding_page.should_be_take_the_tour_button_text()
        molding_page.tap_take_the_tour_button()
        # Double tap control
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_double_tap_control_title()
        learn_more_page.should_be_double_tap_control_message()
        learn_more_page.should_be_double_tap_control_video()
        learn_more_page.swipe_left()
        # Custom Control
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_custom_control_title()
        learn_more_page.should_be_custom_control_message()
        learn_more_page.should_be_custom_control_image()
        learn_more_page.swipe_left()
        # Switching devices
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_switching_devices_title()
        learn_more_page.should_be_switching_devices_message()
        learn_more_page.should_be_switching_devices_image()
        learn_more_page.swipe_left()
        # EQ Customization
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_eq_customization_title()
        learn_more_page.should_be_eq_customization_message()
        learn_more_page.should_be_eq_customization_image()
        learn_more_page.swipe_left()
        # Test Your Fit
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_tyf_title()
        learn_more_page.should_be_tyf_message()
        learn_more_page.should_be_tyf_image()
        learn_more_page.swipe_left()
        # Pair a new device
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_pair_device_title()
        learn_more_page.should_be_pair_device_message()
        learn_more_page.should_be_pair_device_animation()
        learn_more_page.should_be_pair_device_notice()
        learn_more_page.swipe_left()
        # Status indicators
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_status_indicators_title()
        learn_more_page.should_be_status_indicators_message()
        learn_more_page.should_be_status_indicators_image()
        learn_more_page.should_be_status_indicators_notice()
        learn_more_page.swipe_right()
        # Pair a new device
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_pair_device_title()
        learn_more_page.should_be_pair_device_message()
        learn_more_page.should_be_pair_device_animation()
        learn_more_page.should_be_pair_device_notice()
        learn_more_page.swipe_right()
        # Test Your Fit
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_tyf_title()
        learn_more_page.should_be_tyf_message()
        learn_more_page.should_be_tyf_image()
        learn_more_page.swipe_right()
        # EQ Customization
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_eq_customization_title()
        learn_more_page.should_be_eq_customization_message()
        learn_more_page.should_be_eq_customization_image()
        learn_more_page.swipe_right()
        # Switching devices
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_switching_devices_title()
        learn_more_page.should_be_switching_devices_message()
        learn_more_page.should_be_switching_devices_image()
        learn_more_page.swipe_right()
        # Custom Control
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_custom_control_title()
        learn_more_page.should_be_custom_control_message()
        learn_more_page.should_be_custom_control_image()
        learn_more_page.swipe_right()
        # Double tap control
        learn_more_page.should_be_close_button()
        learn_more_page.should_be_double_tap_control_title()
        learn_more_page.should_be_double_tap_control_message()
        learn_more_page.should_be_double_tap_control_video()
        # Quit
        learn_more_page.tap_close_button()
        home_page.should_be_earbuds_name()

    # Additional molding test
    def test_curring_mode_activation2(self, driver):
        welcome_page = WelcomePage(driver)
        demo_commands_page = DemoSendCommandsPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.go_to_demo_screen_code()
        welcome_page.tap_screen_code_get_started()
        time.sleep(6)
        demo_commands_page.should_be_demo_molding_screen()
        demo_commands_page.tap_debug_button()
        demo_commands_page.activate_curring_mode()

    def test_molding_complete1(self, driver):
        analytics_page = AnalyticsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        molding_page.wait_for_connection()
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        time.sleep(19)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(6)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        time.sleep(45)
        molding_page.should_be_progress_bar()
        time.sleep(40)
        # Congratulations
        molding_page.should_congratulations_title()
        molding_page.should_congratulations_subtitle_after_first_molding()
        molding_page.should_be_take_the_tour_button()
        molding_page.should_be_take_the_tour_button_text()
        molding_page.should_skip_for_now_button()
        molding_page.should_skip_for_now_button_text()
        molding_page.tap_skip_for_now_button()
        # Home screen
        home_page.should_be_earbuds_name()
        home_page.should_be_connected_state()
        home_page.should_be_hamburger_menu_icon()
        home_page.should_be_settings_icon()
        home_page.should_be_left_earbud_image()
        home_page.should_be_left_battery_image()
        home_page.should_be_left_battery_percents()
        home_page.should_be_right_earbud_image()
        home_page.should_be_right_battery_image()
        home_page.should_be_right_battery_percents()
        home_page.should_be_case_image()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()

    # Additional molding test
    def test_curring_mode_activation3(self, driver):
        welcome_page = WelcomePage(driver)
        demo_commands_page = DemoSendCommandsPage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.tap_welcome_screen_10_times()
        welcome_page.should_be_welcome_code_screen_title()
        welcome_page.go_to_demo_screen_code()
        welcome_page.tap_screen_code_get_started()
        time.sleep(6)
        demo_commands_page.should_be_demo_molding_screen()
        demo_commands_page.tap_debug_button()
        demo_commands_page.activate_curring_mode()

    def test_molding_complete2(self, driver):
        analytics_page = AnalyticsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        landing_page = LandingPage(driver)
        molding_page = MoldingPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        molding_page.wait_for_connection()
        molding_page.should_be_try_them_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_get_ready_page_title()
        molding_page.tap_main_button()
        molding_page.should_be_how_is_bass_title()
        time.sleep(19)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle1()
        time.sleep(6)
        molding_page.should_be_starting_soon_title()
        molding_page.should_be_starting_soon_subtitle2()
        time.sleep(45)
        molding_page.should_be_progress_bar()
        time.sleep(40)
        # Congratulations
        molding_page.should_congratulations_title()
        molding_page.should_congratulations_subtitle_after_first_molding()
        molding_page.should_be_take_the_tour_button()
        molding_page.should_be_take_the_tour_button_text()
        molding_page.should_skip_for_now_button()
        molding_page.should_skip_for_now_button_text()
        molding_page.tap_skip_for_now_button()
        # Home screen
        home_page.should_be_earbuds_name()
        home_page.should_be_connected_state()
        home_page.should_be_hamburger_menu_icon()
        home_page.should_be_settings_icon()
        home_page.should_be_left_earbud_image()
        home_page.should_be_left_battery_image()
        home_page.should_be_left_battery_percents()
        home_page.should_be_right_earbud_image()
        home_page.should_be_right_battery_image()
        home_page.should_be_right_battery_percents()
        home_page.should_be_case_image()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()

    # EQ presets page
    def test_initial_presets_screen_setup(self, driver):
        analytics_page = AnalyticsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        home_page.wait_for_connection()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()
        eq_presets_page.should_be_toolbar()
        eq_presets_page.should_be_customize_button()
        eq_presets_page.should_be_customize_button_text()
        eq_presets_page.should_be_expandable_part()
        eq_presets_page.should_be_divider_line()
        eq_presets_page.should_be_presets_title()
        eq_presets_page.should_be_edit_button()
        eq_presets_page.should_be_edit_button_text()
        eq_presets_page.should_be_add_button()
        eq_presets_page.should_be_presets_list()
        eq_presets_page.should_be_six_presets()
        eq_presets_page.should_be_initial_preset_order()

    def test_switching_between_eq_presets(self, driver):
        analytics_page = AnalyticsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        home_page.wait_for_connection()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()
        eq_presets_page.should_be_toolbar()
        eq_presets_page.should_be_expandable_part()
        eq_presets_page.select_6_preset()
        eq_presets_page.select_1_preset()
        eq_presets_page.select_5_preset()
        eq_presets_page.select_2_preset()
        eq_presets_page.select_3_preset()
        eq_presets_page.select_4_preset()

    def test_access_edit_presets_screen(self, driver):
        analytics_page = AnalyticsPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        landing_page = LandingPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.should_be_correct_welcome_title()
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.should_be_analytics_title()
        analytics_page.tap_share_analytics_button()
        landing_page.should_be_landing_page_title()
        home_page.wait_for_connection()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.should_be_eq_expand_icon()
        eq_presets_page.should_be_eq_name()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_eq_curve_image()
        eq_presets_page.should_be_toolbar()
        eq_presets_page.should_be_expandable_part()
        eq_presets_page.tap_edit_button()
        edit_preset_page.should_be_toolbar()
        edit_preset_page.should_be_back_arrow()
        edit_preset_page.should_be_edit_preset_title()
        edit_preset_page.should_be_save_button()
        edit_preset_page.should_be_save_button_text()
        edit_preset_page.should_be_presets_list()
        edit_preset_page.should_be_six_presets()
        edit_preset_page.should_be_initial_preset_order()

    def test_preset_reorder_should_be_possible(self, driver):
        analytics_page = AnalyticsPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        home_page.wait_for_connection()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_edit_button()
        edit_preset_page.move_first_preset_to_fourth_position()
        edit_preset_page.move_six_preset_to_second_position()
        edit_preset_page.move_three_to_four_position()

    def test_reordering_should_not_be_saved_after_tapping_back_button(self, driver):
        analytics_page = AnalyticsPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        home_page.wait_for_connection()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.scroll_down()
        time.sleep(3)
        eq_presets_page.should_be_initial_preset_order()
        eq_presets_page.tap_edit_button()
        edit_preset_page.move_second_preset_to_fourth_position()
        edit_preset_page.tap_back_arrow()
        time.sleep(3)
        eq_presets_page.should_be_initial_preset_order()

    def test_reordering_should_be_saved_after_tapping_save_button(self, driver):
        analytics_page = AnalyticsPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        home_page.wait_for_connection()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_edit_button()
        edit_preset_page.move_first_preset_to_fourth_position()
        edit_preset_page.tap_save_button()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.background_app_for_5_seconds()
        eq_presets_page.should_be_preset_order_after_moving_ue_signature_to_fourth()

    def test_reorder_and_delete_first_item(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_preset_page = EditPresetsDialogPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        home_page.wait_for_connection()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_edit_button()
        edit_preset_page.move_first_preset_to_fourth_position()
        edit_preset_page.delete_top_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_five_presets()
        edit_preset_page.tap_save_button()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_five_presets()

    def test_cancel_preset_deletion(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_preset_page = EditPresetsDialogPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        home_page.wait_for_connection()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_edit_button()
        edit_preset_page.delete_sixth_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_cancel_button()
        edit_preset_page.should_be_six_presets()
        edit_preset_page.tap_save_button()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_six_presets()

    def test_delete_all_presets(self, driver):
        analytics_page = AnalyticsPage(driver)
        dialog_preset_page = EditPresetsDialogPage(driver)
        edit_preset_page = EditPresetsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        home_page.wait_for_connection()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_edit_button()
        # Delete preset #6
        edit_preset_page.delete_sixth_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_five_presets()
        # Delete preset #5
        edit_preset_page.delete_fifth_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_four_presets()
        # Delete preset #4
        edit_preset_page.delete_fourth_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_three_presets()
        # Delete preset #3
        edit_preset_page.delete_third_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_two_presets()
        # Delete preset #2
        edit_preset_page.delete_top_preset()
        dialog_preset_page.should_be_dialog_title()
        dialog_preset_page.should_be_dialog_message()
        dialog_preset_page.tap_delete_button()
        edit_preset_page.should_be_one_preset()
        edit_preset_page.tap_save_button()
        eq_presets_page.should_be_ue_signature_eq_selected()
        eq_presets_page.should_be_one_preset()

    def test_access_new_preset_editor(self, driver):
        analytics_page = AnalyticsPage(driver)
        eq_presets_page = EqPresetsPage(driver)
        eq_preset_setup_page = EqPresetSetupPage(driver)
        home_page = HomePage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        home_page.wait_for_connection()
        home_page.should_be_connected_state()
        eq_presets_page.tap_eq_expand_icon()
        eq_presets_page.tap_add_button()
        eq_preset_setup_page.should_be_toolbar()
        eq_preset_setup_page.should_be_new_preset_setup_title()
        eq_preset_setup_page.should_be_eq_editor()
        eq_preset_setup_page.should_be_history_title()
        eq_preset_setup_page.should_be_backward_arrow()
        eq_preset_setup_page.should_be_forward_arrow()
        eq_preset_setup_page.should_be_history_progress_bar()
        eq_preset_setup_page.tap_back_arrow()
        eq_presets_page.should_be_initial_preset_order()

    # Mold new tips page
    def test_mold_new_tips_carousel(self, driver):
        analytics_page = AnalyticsPage(driver)
        home_page = HomePage(driver)
        menu_page = MenuPage(driver)
        mold_new_tips_page = MoldNewTipsPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        home_page.wait_for_connection()
        home_page.should_be_earbuds_name()
        home_page.tap_hamburger_menu_icon()
        menu_page.tap_mold_new_tips_item()
        # Change your tips
        mold_new_tips_page.should_be_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.should_be_next_button_text()
        mold_new_tips_page.next_button_not_enabled()
        mold_new_tips_page.should_be_image_item()
        mold_new_tips_page.should_be_change_tips_title()
        mold_new_tips_page.should_be_change_tips_subtitle()
        # Remove inserts
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.should_be_next_button_text()
        mold_new_tips_page.next_button_not_enabled()
        mold_new_tips_page.should_be_image_item()
        mold_new_tips_page.should_be_remove_inserts_title()
        mold_new_tips_page.should_be_remove_inserts_subtitle()
        # Match them up
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.should_be_next_button_text()
        mold_new_tips_page.next_button_not_enabled()
        mold_new_tips_page.should_be_image_item()
        mold_new_tips_page.should_be_match_them_up_title()
        mold_new_tips_page.should_be_match_them_up_subtitle()
        # Attach your tips
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.should_be_next_button_text()
        mold_new_tips_page.next_button_not_enabled()
        mold_new_tips_page.should_be_image_item()
        mold_new_tips_page.should_be_attach_your_tips_title()
        mold_new_tips_page.should_be_attach_your_tips_subtitle()
        # Check the fit
        mold_new_tips_page.swipe_left()
        mold_new_tips_page.should_be_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.should_be_next_button_text()
        mold_new_tips_page.next_button_enabled()
        mold_new_tips_page.should_be_image_item()
        mold_new_tips_page.should_be_check_the_fit_title()
        mold_new_tips_page.should_be_check_the_fit_subtitle()
        # Attach your tips
        mold_new_tips_page.swipe_right()
        mold_new_tips_page.should_be_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.should_be_next_button_text()
        mold_new_tips_page.next_button_enabled()
        mold_new_tips_page.should_be_image_item()
        mold_new_tips_page.should_be_attach_your_tips_title()
        mold_new_tips_page.should_be_attach_your_tips_subtitle()
        # Match them up
        mold_new_tips_page.swipe_right()
        mold_new_tips_page.should_be_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.should_be_next_button_text()
        mold_new_tips_page.next_button_enabled()
        mold_new_tips_page.should_be_image_item()
        mold_new_tips_page.should_be_match_them_up_title()
        mold_new_tips_page.should_be_match_them_up_subtitle()
        # Remove inserts
        mold_new_tips_page.swipe_right()
        mold_new_tips_page.should_be_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.should_be_next_button_text()
        mold_new_tips_page.next_button_enabled()
        mold_new_tips_page.should_be_image_item()
        mold_new_tips_page.should_be_remove_inserts_title()
        mold_new_tips_page.should_be_remove_inserts_subtitle()
        # Change your tips
        mold_new_tips_page.swipe_right()
        mold_new_tips_page.should_be_menu_icon()
        mold_new_tips_page.should_be_scroll_dots()
        mold_new_tips_page.should_be_next_button()
        mold_new_tips_page.should_be_next_button_text()
        mold_new_tips_page.next_button_enabled()
        mold_new_tips_page.should_be_image_item()
        mold_new_tips_page.should_be_change_tips_title()
        mold_new_tips_page.should_be_change_tips_subtitle()
        # Return to Home screen
        mold_new_tips_page.tap_menu_icon()
        menu_page.tap_home_item()
        home_page.should_be_earbuds_name()

    def test_mold_new_tips_molding(self, driver):
        analytics_page = AnalyticsPage(driver)
        home_page = HomePage(driver)
        menu_page = MenuPage(driver)
        mold_new_tips_page = MoldNewTipsPage(driver)
        welcome_page = WelcomePage(driver)
        welcome_page.tap_welcome_screen_get_started()
        analytics_page.tap_share_analytics_button()
        home_page.wait_for_connection()
        home_page.should_be_earbuds_name()
        home_page.tap_hamburger_menu_icon()
        menu_page.tap_mold_new_tips_item()
        # Change your tips
        mold_new_tips_page.should_be_change_tips_title()
        mold_new_tips_page.swipe_left()
        # Remove inserts
        mold_new_tips_page.should_be_remove_inserts_title()
        mold_new_tips_page.swipe_left()
        # Match them up
        mold_new_tips_page.should_be_match_them_up_title()
        mold_new_tips_page.swipe_left()
        # Attach your tips
        mold_new_tips_page.should_be_attach_your_tips_title()
        mold_new_tips_page.swipe_left()
        # Check the fit
        mold_new_tips_page.should_be_check_the_fit_title()
        mold_new_tips_page.tap_next_button()
        # Try them on
        mold_new_tips_page.wait_for_connection()
        mold_new_tips_page.should_be_try_them_page_title()
        mold_new_tips_page.tap_main_button()
        mold_new_tips_page.should_be_get_ready_page_title()
        mold_new_tips_page.tap_main_button()
        mold_new_tips_page.should_be_how_is_bass_title()
        time.sleep(19)
        mold_new_tips_page.should_be_starting_soon_title()
        mold_new_tips_page.should_be_starting_soon_subtitle1()
        time.sleep(6)
        mold_new_tips_page.should_be_starting_soon_title()
        mold_new_tips_page.should_be_starting_soon_subtitle2()
        time.sleep(45)
        mold_new_tips_page.should_be_progress_bar()
        time.sleep(40)
        # Congratulations
        mold_new_tips_page.should_congratulations_title()
        mold_new_tips_page.should_be_finish_button()
        mold_new_tips_page.should_be_finish_button_text()
        mold_new_tips_page.tap_finish_button()
        # Home screen
        home_page.should_be_earbuds_name()

# run with
# pytest -s -v --reruns 1 -m smoke_test --html=/Users/rudiuk/PyCharmProjects/test_appium_project/test_report/report.html --capture sys
